object Versions {
    const val androidCore = "1.10.1"
    const val appCompat = "1.6.1"
    const val constraint = "2.1.4"
    const val coroutinesCore = "1.7.1"
    const val daggerHilt = "2.46.1"
    const val epoxy = "4.1.0"
    const val espresso = "3.5.1"
    const val javaxInject = "1"
    const val junit = "4.13.2"
    const val junitTest = "1.1.5"
    const val lifecycle = "2.6.1"
    const val material = "1.9.0"
    const val moshi = "1.13.0"
    const val navigation = "2.5.3"
    const val okhttp = "4.11.0"
    const val retrofit = "2.9.0"
    const val splashScreen = "1.0.1"
    const val swipeRefreshLayout = "1.1.0"
    const val timber = "5.0.1"
}
